# rgname            = "kholer-rg"
# location          = "australiaeast"
# vnetname          = "kholer-rg-vnet"
# address_space     = "10.50.0.0/16"
# subnet_name       = "kholer-rg-svc-subnet"
# delegation_name   = "kholer-app-delegation"
# address_prefixes  = "10.50.2.0/24"
# app_svc_plan_name = "kholer-svc-plan"
# tier              = "Standard"
# size              = "S1"
# app_svc_name      = "kohler-myappsvc"

rgname            = "__rgname__"
location          = "__location__"
vnetname          = "__vnetname__"
address_space     = "__address_space__"
subnet_name       = "__subnet_name__"
delegation_name   = "__delegation_name__"
address_prefixes  = "__address_prefixes__"
app_svc_plan_name = "__app_svc_plan_name__"
tier              = "__tier__"
size              = "__size__"
app_svc_name      = "__app_svc_name__"

