a = input("enter your no. :- ")
a = int(a)
print(a)
b = input("enter your no. :- ")
b = int(b)
print(b)
c = input("enter your no. :- ")
c = int(c)
print(c)
d = input("enter your no. :- ")
d = int(d)
print(d)
e = input("enter your no. :- ")
e = int(e)
print(e)
print("avg of all no. is :- ", ((a+b+c+d+e)/2))