apiVersion: apps/v1
kind: Deployment
metadata:
  name: myd1
spec:
  replicas: 3
  selector: 
    matchLabels:
      env: prod
  template:
    metadata:
      name: "wpod"
      labels:
        env: prod

    spec:
       volumes:
       containers:
       - name: "webc1"
         image: "vimal13/apache-webserver-php" 
        