apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv3
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "192.168.43.73"
    path: "/mydata"
