apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv1
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: "172.31.93.80"
    path: "/mydata1"

