- hosts: all
  vars:
      - dvd_dir: "/dvd"
  tasks:
    - file:
        state: directory
        path: "{{ dvd_dir }}"

    - mount:
        src: "/dev/cdrom"
        path: "{{ dvd_dir }}"
        state: mounted
        fstype: iso9660

    - yum_repository:
        baseurl: "{{ dvd_dir }}/AppStream"
        name: "dvd1"
        description: "AppStream dvd"
        gpgcheck: no

    - yum_repository:
        baseurl: "{{ dvd_dir }}/BaseOS"
        name: "dvd2"
        description: "BaseOS dvd"
        gpgcheck: no

    - yum_repository:
        baseurl: "https://download.docker.com/linux/centos/7/x86_64/stable/"
        name: "docker-ce"
        description: "Docker-ce repo"
        gpgcheck: no

    - package:
        name: "python3"
        state: present

    - package:
        name: "docker-ce-18.09.1-3.el7.x86_64"
        state: present

    - pip:
        name: "docker-py"

    - service:
        name: "docker"
        state: started
        enabled: yes

    - file:
        state: directory
        path: "/htmlpages"

    - copy:
        dest: "/htmlpages/docker.html"
        content: "Welcome to Docker page!!"

    - docker_image:
        name: "httpd:latest"
        source: pull

    - docker_container:
        name: "webserver"
        image: "httpd:latest"
        state: started
        exposed_ports: "80"
        ports: "8081:80"
        volumes: "/htmlpages:/usr/local/apache2/htdocs/"








